### ISSUE TITLE
Module 5 - Exercise Feedback

### ISSUE THREAD

**Issue by Kamidala** [katiemwells/katiewells-MADA-portfolio#3]
Hello Katie!

I'm quite impressed that you chose to use plotly, as I have not yet looked into this package (ggplot2 is more familiar territory, haha). It seems that the shape of the main graph is a bit off (more rectangular than square), but that could probably be adjusted through a scaling function. You could also change transparency for the other points by using alpha = 0.5 (or whatever value you would like). Overall, very nice recreation of the original plot!

**Comment by katiemwells** [comment]
Thanks for the feedback Kai! I changed the alpha and the size of the points to make them match the original a bit better. I played with the scale a little and got it to match the original, but it still left it more rectangular than square. I think I'll keep it this way for now but I'll keep searching for a way to make it just that much closer to the original.
